---
locale: es
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices:
- value: "`rehabilitar` en `EstudianteDeVeterinaria`."
  checked: true
- value: "`recibir_rehabilitacion` en `Gato`."
  checked: true
- value: "`recibir_rehabilitacion` en `Caballo`."
  checked: true
- value: "`recibir_rehabilitacion` en `Golondrina`."
  checked: true
name: Tratame indistintamente
