---
locale: es
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`rehabilitar` en `EstudianteDeVeterinaria`."
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`recibir_rehabilitacion` en `Gato`."
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`recibir_rehabilitacion` en `Caballo`."
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`recibir_rehabilitacion` en `Golondrina`."
  checked: true
name: Nuevo ejercicio
