---
locale: es
tags: []
layout: input_bottom
editor: 0
type: interactive
extra_visible: false
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices: []
goal:
  kind: queries_match
  regexps:
  - "^pelu.rehabilitar\\s*\\(\\s*theo\\s*\\)\\s*$"
  - "^pelu.rehabilitar\\s*\\(\\s*tornado\\s*\\)\\s*$"
  - "^pelu.rehabilitar\\s*\\(\\s*norita\\s*\\)\\s*$"
name: Puede fallar
